# Generated by Django 2.2.12 on 2022-02-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caissier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.IntegerField(max_length=100, verbose_name='Nom')),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='etudiants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prenom')),
                ('sexe', models.CharField(max_length=30, verbose_name='Sexe')),
                ('filiere', models.CharField(max_length=100, verbose_name='Filière')),
                ('niveau', models.CharField(max_length=30, verbose_name='Niveau')),
                ('statut', models.CharField(max_length=30, verbose_name='Statut')),
                ('num_matricule', models.CharField(max_length=30, verbose_name='Num_matricule')),
            ],
        ),
        migrations.CreateModel(
            name='payements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payement', models.CharField(max_length=100, verbose_name='Date_payement')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('montant', models.DateField(verbose_name='Montant')),
                ('avance', models.CharField(max_length=200, verbose_name='Avance')),
                ('reste', models.IntegerField(verbose_name='Reste')),
                ('rendez_vous', models.CharField(max_length=120, verbose_name='Rendez_vous')),
                ('etudiants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse_22.etudiants')),
            ],
        ),
        migrations.CreateModel(
            name='Enregistrements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_enregist', models.CharField(max_length=120, verbose_name='Ref_enregistrement')),
                ('date_enregist', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.CharField(max_length=120, verbose_name='Auteur')),
                ('caissier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse_22.Caissier')),
                ('payements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse_22.payements')),
            ],
        ),
        migrations.CreateModel(
            name='caisses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_caisses', models.CharField(max_length=100, verbose_name='Ref_caisses')),
                ('montant', models.CharField(max_length=100, verbose_name='Montant')),
                ('statut', models.CharField(max_length=100, verbose_name='Statut')),
                ('commentaire', models.CharField(max_length=200, verbose_name='Commentaire')),
                ('caisiers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse_22.Caissier')),
            ],
        ),
    ]
