# Generated by Django 2.2.12 on 2022-02-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse_22', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisses',
            name='montant',
            field=models.IntegerField(max_length=100, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='caissier',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='enregistrements',
            name='date_enregist',
            field=models.DateTimeField(max_length=200, verbose_name='Date_enregistrement'),
        ),
        migrations.AlterField(
            model_name='payements',
            name='avance',
            field=models.IntegerField(max_length=200, verbose_name='Avance'),
        ),
        migrations.AlterField(
            model_name='payements',
            name='date_payement',
            field=models.DateField(max_length=100, verbose_name='Date_payement'),
        ),
        migrations.AlterField(
            model_name='payements',
            name='montant',
            field=models.IntegerField(verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='payements',
            name='rendez_vous',
            field=models.DateField(max_length=120, verbose_name='Rendez_vous'),
        ),
    ]
